steps:
# Build API image
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build API image'
  args: [
    'build',
    '.',
    '-t',
    'europe-west3-docker.pkg.dev/$PROJECT_ID/my-container-registry/mlops-api:latest',
    '-f',
    'dockerfiles/api.dockerfile'
  ]

# Push API image
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push API image'
  args: [
    'push',
    'europe-west3-docker.pkg.dev/$PROJECT_ID/my-container-registry/mlops-api:latest'
  ]

# Deploy to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Deploy to Cloud Run'
  args: [
    'run',
    'deploy',
    'financial-sentiment-api',
    '--image',
    'europe-west3-docker.pkg.dev/$PROJECT_ID/my-container-registry/mlops-api:latest',
    '--region',
    'europe-west3',
    '--platform',
    'managed',
    # inject secrets as environment variables
    '--update-secrets=WANDB_API_KEY=WANDB_API_KEY:latest'
  ]

#Run API Tests and Save
- name: Auth with GCP
  uses: google-github-actions/auth@v2
  with:
    credentials_json: ${{ secrets.GCP_SA_KEY }}

- name: Set up Cloud SDK
  uses: google-github-actions/setup-gcloud@v2

- name: Extract deployed model URL
  run: |
    DEPLOYED_MODEL_URL=$(gcloud run services describe financial-sentiment-api \
      --region=europe-west3 \
      --format='value(status.url)')
    echo "DEPLOYED_MODEL_URL=$DEPLOYED_MODEL_URL" >> $GITHUB_ENV

- name: Run load test on deployed model
  env:
    DEPLOYED_MODEL_URL: ${{ env.DEPLOYED_MODEL_URL }}
  run: |
    locust -f tests/locustfile.py \
      --headless -u 50 -r 5 --run-time 5m --host=$DEPLOYED_MODEL_URL --csv=/locust/results

- name: Upload locust results
  uses: actions/upload-artifact@v4
  with:
    name: locust-results
    path: /locust

options:
  logging: CLOUD_LOGGING_ONLY
