steps:

# Build API image
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build API image'
  args: [
    'build',
    '.',
    '-t',
    'europe-west3-docker.pkg.dev/$PROJECT_ID/my-container-registry/mlops-api:latest',
    '-f',
    'dockerfiles/api.dockerfile'
  ]

# Push API image
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push API image'
  args: [
    'push',
    'europe-west3-docker.pkg.dev/$PROJECT_ID/my-container-registry/mlops-api:latest'
  ]

# Deploy to Cloud Run using enhanced monitoring config
# This will apply full deployment config including memory, environment variables,
# execution environment, container dependencies (for Prometheus sidecar), etc.
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Deploy to Cloud Run (monitoring version)'
  args: [
    'run',
    'services',
    'replace',
    'cloudbuild/cloudrun_monitoring.yaml',
    '--region=europe-west3',
    '--platform=managed',
    '--project=${PROJECT_ID}'
  ]

options:
  logging: CLOUD_LOGGING_ONLY
