steps:
# Build training image
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build container image'
  args: [
    'build',
    '.',
    '-t',
    'europe-west3-docker.pkg.dev/$PROJECT_ID/my-container-registry/mlops-train:latest',
    '-f',
    'dockerfiles/train.dockerfile'
  ]
# Push training image
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push container image'
  args: [
    'push',
    'europe-west3-docker.pkg.dev/$PROJECT_ID/my-container-registry/mlops-train:latest'
  ]
options:
  logging: CLOUD_LOGGING_ONLY