_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.11.3
        t:
            "1":
                - 1
                - 11
                - 49
                - 105
            "2":
                - 1
                - 11
                - 49
                - 105
            "3":
                - 1
                - 3
                - 16
                - 55
            "4": 3.11.3
            "5": 0.20.1
            "6": 4.52.4
            "8":
                - 3
            "12": 0.20.1
            "13": windows-amd64
batch_size:
    value: 32
data_dir:
    value: ./data/processed
epochs:
    value: 5
lr:
    value: 0.001
max_rows:
    value: 100
seed:
    value: 42
