# Experiment general settings
experiment_name: "financial_sentiment_analysis"
seed: 42
epochs: 5
batch_size: 32

# Data-related configs
data:
  data_dir: "./data/processed"
  max_rows: 100

# Model hyperparameters
model:
  model_name: "Classifier"
  lr: 0.001
  dropout: 0.3
  num_layers: 2
  hidden_dim: 256
